// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// prisma.config.ts
import { defineConfig } from '@prisma/config';

export default defineConfig({
  datasource: {
    // This points to your environment variable
    url: process.env.DATABASE_URL,
  },
});